mass-per-transaction: 1.0
maximum-mass: 1000.0
max-pct-change: 0.05
var-multiplier: 0.02
mass-var-min: 1.0
mass-var-max: 0.1
price-spread: 0.05
surcharge-curve-epsilon: 0.001
clamp-multiplier: 0.5
starting-mass: 5