# The default amount of money a player has in their wallet before buying/selling
default-wallet: 420.69
# Whether the frames containing items should be shown
visible-frames: true
# How frequently prices should automatically update (in ticks)
ticks-between-price-motion: 1
# The number of items to update per price motion
items-to-update-per-price-motion: 1
# The maximum number of stacks of items that can be bought at once
max-stacks-purchase: 36


# Whether to send additional debug messages to the console.
debug-messages: false


# How much mass is added per transaction (affects how hard it is to change the price of an item)
mass-per-transaction: 5.0
# The starting mass of an item
starting-mass: 5.0
# The highest value that mass can reach
maximum-mass: 100000.0
# The default price of a particular piece of merchandise if not found in mechprices.yml
default-merch-price: 10.0
# The default price of a particular type of enchantment if not found in enchantment.yml
default-enchantment-price: 100.0
# A multiplier that affects how much price is affected by bigger purchases
purchase-size-multiplier: 1.0
# The maximum percentage a price can change per update (including transactions)
max-pct-change: 0.05
# A multiplier which influences how much a price can vary from its best-guess price. Higher values make prices more volatile.
var-multiplier: 0.02
# How much mass affects the price of an item. Higher values make prices more volatile.
mass-var-min: 1.0
mass-var-max: 0.00001
# How much mass affects the pushAmount of an item when it is bought. Higher values make prices more volatile.
# Basically gets the current mass of the item, interpolates, then multiplies pushAmount by the interpolated value.
# min refers to minimum mass, max refers to maximum mass.
mass-push-min-mult: 1.0
mass-push-max-mult: 0.01
# Depending on the surcharge-curve-epsilon, the price-spread below will need to be different. A couple values are:
# For surcharge-curve-epsilon = 0, any non-negative price spread works
# For surcharge-curve-epsilon = 0.1, price spread should be >= 0.195
# For surcharge-curve-epsilon = 0.01, price spread should be >= 0.0195 (notice the added 0 for both sides)
# For surcharge-curve-epsilon = 0.05, price spread should be >= 0.0975
# See here: https://www.desmos.com/calculator/vdtvxilbpj
price-spread: 0.05
# epsilon of 0.05 and spread of 0.0001 means that buying 1 item charges ₿0.626 per transaction and buying 64 items charges ₿0.50 per transaction
surcharge-curve-epsilon: 0.0001
# Affects how much the price should try to correct towards the best-guess price. Higher values make corrections more aggressive.
clamp-multiplier: 0.5
