name: FantasyCostco
main: games.skweekychair.fantasycostco.CostcoPlugin
version: 1.1.0
api-version: 1.18

commands:
  buy:
    description: Buy some quantity of specified item from server, as specified by your buy-possible setting. Quantity is optional.
    usage: /<command> [item] [quantity (0..1728) (optional)]
    permission: fantastycostco.buy
  sell:
    description: Sell item stack in hand to the server
    usage: /<command>
    permission: fantasycostco.sell
  get-wallet:
    description: Get how many Blockcoins are in your wallet
    usage: /<command>
    permission: fantasycostco.wallet
    aliases:
      - wallet
      - balance
  set-wallet:
    description: Set how many Blockcoins a player has in their wallet. If player is not specified, assumes the player who sent the command, unless they are not a player.
    usage: /<command> [amount (a number)] [player (optional)]
    permission: fantasycostco.set-wallet
  buy-as-much-as-possible:
    description: Get, set, or toggle whether you will buy as much as possible when you can't afford what you requested.
    usage: /<command> [true | false | get]
    permission: fantasycostco.buy-possible
    aliases:
      - buy-possible
      - buy-amap
  amount:
    description: Set or get the number of items you want to try to buy.
    usage: /<command> [quantity (0..2304) | get]
    permission: fantasycostco.buy-amount
    aliases:
      - buy-amount
  use-amount:
    description: Whether to use the amount setting when buying items. If set to false, just buys what the sign has listed.
    usage: /<command> [true | false | get]
    permission: fantasycostco.use-amount
    aliases:
      - use-buy-amount
  just-looking:
    description: Get, set, or toggle whether you're "just looking" or actually buying/selling items. If this is true, you will not buy or sell items but can still see how much items cost.
    usage: /<command> [true | false | get]
    permission: fantasycostco.just-looking
  ordain:
    description: Get, set, or toggle whether you want to ordain a sign to allow players to buy items.
    usage: /<command> [true | false | get]
    permission: fantasycostco.ordain-sign
  balance-top:
    description: Get the players with the most Blockcoins in the server.
    usage: /<command> [page (1..x) (optional)]
    permission: fantasycostco.balance-top
  pay:
    description: Pay another player some Blockcoins.
    usage: /<command> [player (name)] [amount (a number)]
    permission: fantasycostco.pay
  update-frames:
    description: Update the item frames near signs
    usage: /<command>
    permission: fantastycostco.update-frames
permissions:
  fantasycostco.buy:
    default: op
  fantasycostco.sell:
    default: op
  fantasycostco.wallet:
    default: true
  fantasycostco.set-wallet:
    default: op
  fantasycostco.buy-possible:
    default: true
  fantasycostco.buy-amount:
    default: true
  fantasycostco.use-amount:
    default: true
  fantasycostco.just-looking:
    default: true
  fantasycostco.ordain-sign:
    default: op
  fantasycostco.balance-top:
    default: true
  fantasycostco.pay:
    default: true
  fantastycostco.update-frames:
    default: op
