name: FantasyCostco
main: games.skweekychair.fantasycostco.CostcoPlugin
version: 0.1
api-version: 1.18

commands:
  buy:
    description: Buy specified quantity of specified item from server
    usage: /<command> [item] [quantity]
    permission: fantastycostco.buy
  sell:
    description: Sell item stack in hand to the server
    usage: /<command>
    permission: fantasycostco.sell
  gui:
    description: Open a GUI
    usage: /<command>
permissions:
  fantasycostco.buy:
    default: true
  fantasycostco.sell:
    default: true
