name: FantasyCostco
main: games.skweekychair.fantasycostco.CostcoPlugin
version: 0.1
api-version: 1.18

commands:
  buy:
    description: Buy specified quantity of specified item from server
    usage: /<command> [item] [quantity]
    permission: fantastycostco.buy
  sell:
    description: Sell item stack in hand to the server
    usage: /<command>
    permission: fantasycostco.sell
  wallet:
    description: Get how many Blockcoins are in your wallet
    usage: /<command>
    permission: fantasycostco.wallet
  set-wallet:
    description: Set how many Blockcoins a player has in their wallet
    usage: /<command> [player] [amount]
    permission: fantasycostco.set-wallet
  toggle-buy-possible:
    description: Toggle whether to attempt to buy as many items as can be afforded in the case that you don't have enough Blockcoins to buy the amount requested.
    usage: /<command>
    permission: fantasycostco.toggle-buy-possible
permissions:
  fantasycostco.buy:
    default: true
  fantasycostco.sell:
    default: true
  fantasycostco.wallet:
    default: true
  fantasycostco.toggle-buy-possible:
    default: true
  fantasycostco.set-wallet:
    default: false
